{% set name = "neutralocean" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neutralocean-{{ version }}.tar.gz
  sha256: 9b9d69b643f7e35573d874943711daf86d5560827bd3e30a6e63357c2d357290

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numba
    - numpy
    - xarray
    - scipy
    - gsw
    - pooch
    - xgcm
    - netcdf4

test:
  imports:
    - neutralocean
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geoffstanley/neutralocean
  summary: Neutral Surfaces in the Ocean
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - geoffstanley
