{% set name = "neutralocean" %}
{% set version = "2.4.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neutralocean-{{ version }}.tar.gz
  sha256: e3ac838b3b17365616884eb2c87995d44012d37e529ffcd0c6e6473e4a4d9490

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numba
    - numpy
    - xarray
    - scipy
    - gsw
    - pooch
    - xgcm
    - netcdf4

test:
  imports:
    - neutralocean
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/geoffstanley/neutralocean
  summary: Neutral Surfaces in the Ocean
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - geoffstanley
